# Prerequisites
brew "mas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# 3rd Party services
tap "stripe/stripe-cli"
brew "stripe/stripe-cli/stripe"

# Development Tools
tap "puma/puma"
brew "puma/puma/puma-dev"

# Shells
brew "fish"

# Misc
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "readline"
brew "asdf"
brew "bat"
brew "glib"
brew "curl"
brew "efm-langserver"
brew "exa"
brew "fd"
brew "fx"
brew "openjdk"
brew "fop"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "git"
brew "gnutls"
brew "gnupg"
brew "gobject-introspection"
brew "harfbuzz"
brew "hub"
brew "pango"
brew "librsvg"
brew "lua-language-server"
brew "graphviz"
brew "jq"
brew "kerl"
brew "libxslt"
brew "openssl@3"
brew "pgcli"
brew "redis"
brew "ripgrep"
brew "subversion"
brew "tealdeer"
brew "tmux"
brew "tree"
brew "unzip"
brew "wxwidgets"
brew "yt-dlp"

cask "barrier"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-for-powerline"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "insomnia"
cask "signal"

# Archive
# brew "neovim"
# cask "wkhtmltopdf"
