#!/bin/bash

CONFIG_FILE_NAME=.workon.conf
PROJECT_LIST_DIR=$HOME/.workon

project_base_dir() {
  PROJECT=$1
  echo "$PROJECT_LIST_DIR/$PROJECT"
}

add_project() {
  PROJECT=$1
  PROJ_PATH=$2

  ABS_PROJ_PATH=$( cd "$PROJ_PATH" && pwd )
  echo "Adding $PROJECT as $ABS_PROJ_PATH"
  mkdir -p $PROJECT_LIST_DIR
  ln -s $ABS_PROJ_PATH $PROJECT_LIST_DIR/$PROJECT

  edit_project $PROJECT
}

edit_project() {
  if [[ "$EDITOR" == "" ]]; then
    echo "No editor defined. Please set \$EDITOR"
    exit
  fi

  PROJECT=$1
  BASE_DIR=$(project_base_dir $PROJECT)
  CONFIG_FILE="$BASE_DIR/$CONFIG_FILE_NAME"

  touch $CONFIG_FILE
  $EDITOR $CONFIG_FILE
}

init() {
  if [[ -f $HOME/.workon/.workon.conf ]]; then
    echo "source $HOME/.workon/.workon.conf"
    echo "/bin/rm $HOME/.workon/.workon.conf"
  fi
}

list_projects() {
  ls -1 $PROJECT_LIST_DIR
}

run_project() {
  export CURRENT_PROJECT=$1

  PROJECT_BASE_DIR="$PROJECT_LIST_DIR/$CURRENT_PROJECT"

  if [[ -f "$PROJECT_BASE_DIR/$CONFIG_FILE_NAME" ]]; then
    cd $PROJECT_BASE_DIR
    PROJECT_ROOT_DIR=$PROJECT_BASE_DIR
    cp $CONFIG_FILE_NAME ~/.workon/.workon.conf

    cd $(readlink $PROJECT_ROOT_DIR)
    exec $SHELL
  else
    echo "The $CURRENT_PROJECT project is not defined. Please add it first."
  fi
}

check_for_config() {
  if [ ! -d $PROJECT_LIST_DIR ]; then
    echo "No projects configured! Add a project before use."
    exit
  fi
}

usage() {
  shell_command=$(basename $0)
  cat <<EOF
Usage:  $shell_command add <project> <project_path>
	     Create a project entry named <project> and edit the project script
             in <project_path>
        $shell_command edit <project>
             Edit the project script in <project_path>
        $shell_command list
             List projects defined in $PROJECT_LIST_DIR
        $shell_command <project>
             Start a shell in <project>'s defined path"
EOF
}

install_instructions() {
  echo "Add the following line to your bashrc/zshrc file."
  echo "source <(workon init)"
}

COMMAND="help"
if [[ "$1" != "" ]]; then
  COMMAND="$1"
  shift
fi

if [[ "$COMMAND" == "add" ]]; then
  add_project $1 $2
elif [[ "$COMMAND" == "edit" ]]; then
  check_for_config
  edit_project $1
elif [[ "$COMMAND" == "init" ]]; then
  init
elif [[ "$COMMAND" == "install" ]]; then
  install_instructions
elif [[ "$COMMAND" == "list" ]]; then
  check_for_config
  list_projects
elif [[ "$COMMAND" == "status" ]]; then
  echo "Current project: ${CURRENT_PROJECT}"
elif [[ "$COMMAND" == "help" ]]; then
  usage
else
  check_for_config
  run_project $COMMAND
fi
