#!/bin/bash

FORCE=false

is_git_repo() {
  git status 1>/dev/null 2>&1
  if [[ $? -eq 0 ]]; then
    echo 'true'
  else
    echo 'false'
  fi
}

clean_name() {
  echo "$1" | sed 's/[* ]//g'
}

co_to_top_branch() {
  git checkout "master" 2>/dev/null

  if [[ $? -ne 0 ]]; then
    git checkout "main" 2>/dev/null
  fi
}

pull_current_dir() {
  echo '----------------------------'
  echo $(basename $(pwd))
  echo '----------------------------'

  if [[ "$FORCE" == "true" ]]; then
    echo "Using force!"

    git restore .
    git clean -fd

    co_to_top_branch
  fi

  git pull 2> >(grep -v 'remote:')
}

if [[ "$1" == "--force" ]]; then
  FORCE=true
fi

if [[ "$(is_git_repo)" == 'true' ]]; then
  pull_current_dir
  # echo '----------------------------'
  # echo $(basename $(pwd))
  # echo '----------------------------'

  # git pull | grep -v 'remote:'
  # if [[ $? -eq 0 ]]; then
  #   echo 'success'
  # else
  #   echo 'failed'
  # fi
else
  echo 'Multi Repo'
  basedir=$(pwd)
  for dir in $(find . -type d -depth 1); do
    cd $dir
    pull_current_dir
    cd $basedir
  done
fi
