#!/bin/bash

file="$1"

if [[ "$file" == "" ]]; then
  echo "usage:"
  echo "mts mediainfo FILE"
  exit -1
fi

echo "Checking '$file'"

mediainfo --Output=JSON --Full "$file" | jq '
  [
    if . | type == "array" then
      .
    else
      [.]
    end |
    to_entries[] |
    .value.media as $media |
    {
      title: (.key + 1),
      filename: $media."@ref",
      general: ($media.track[] | select(."@type" == "General")),
      video: ($media.track[] | select(."@type" == "Video")),
      # audio: ($media.track[] | select(."@type" == "Audio")[]),
    }
  ] |
  sort_by(.general.Duration) |
  reverse |
  [
    .[] |
    {
      title: .title,
      # video_title1: .general.Title,
      # video_title2: .general.Title_More,
      # video_title3: .general.Title_Url,
      # filename: .filename,
      duration: .general.Duration_String2,
      # audio_tracks: .audio.Title,
      # audio_languages: .audio.Language_String,
    }
  ]
'
